"""
作家种子数据 — 来源：作家完整档案.docx（60位作家）
seed(db) 是幂等的，使用 INSERT OR REPLACE。
"""

SEED_WRITERS = [
    {
        "writer_id": "poe",
        "name": "埃德加·爱伦·坡",
        "name_en": "Edgar Allan Poe",
        "avatar_initial": "坡",
        "bio": "1809—1849。推理小说鼻祖，把「侦探推理」写成文学的第一人。",
        "personality_tags": ["忧郁", "神秘", "敏感", "诡美"],
        "suitable_personality": "内向敏感、想象力强、情绪细腻、容易沉浸内心世界；偏爱幽暗美学，不排斥悲伤",
        "suitable_life_state": "内心情绪复杂、难以向外言说；喜欢深夜独处；对人性阴暗面有天然好奇",
        "value_resonance": "美可以存在于黑暗中；拒绝廉价快乐；相信真实比光明更重要",
        "suitable_timing": "想探索内心阴影；不想被治愈，只想被理解；情绪细腻但不愿被打扰",
        "emotional_tone": "清冷、神秘、被看穿、深度共鸣",
        "contra_indicators": "追求阳光励志；需要轻松快乐；讨厌压抑、暗黑氛围",
        "recommendation_style": "你内心的细腻与幽暗，只有他能精准接住，不是治愈，是懂得。",
        "works": [
            {"title": "厄舍府的倒塌", "year": 1839, "description": "哥特式恐怖短篇，心理恐惧的极致"},
            {"title": "莫格街凶杀案", "year": 1841, "description": "世界第一篇推理小说"},
            {"title": "乌鸦", "year": 1845, "description": "最著名诗歌，忧郁与孤独的象征"},
        ],
    },
    {
        "writer_id": "chekhov",
        "name": "安东·契诃夫",
        "name_en": "Anton Chekhov",
        "avatar_initial": "契",
        "bio": "1860—1904。俄国短篇大师，本职是医生，写作只是副业。",
        "personality_tags": ["冷静", "克制", "温和", "悲悯"],
        "suitable_personality": "温和内敛、观察力强、不爱争辩、内心柔软但理性",
        "suitable_life_state": "在平淡日常里寻找意义；面对人性复杂但不愿偏激；需要安静理解",
        "value_resonance": "平凡生活有重量；理解大于说教；温柔比激烈更有力量",
        "suitable_timing": "不想被鸡汤；需要安静陪伴；想看清生活本来样子",
        "emotional_tone": "平静、温柔、清醒、被懂得",
        "contra_indicators": "追求强烈刺激；需要明确答案；喜欢热血励志",
        "recommendation_style": "你这种安静又清醒的人，最适合他那种不喧哗的温柔。",
        "works": [
            {"title": "樱桃园", "year": 1904, "description": "最后一部剧作，时代流逝的挽歌"},
            {"title": "套中人", "year": 1898, "description": "短篇经典，封闭自我的讽刺"},
            {"title": "海鸥", "year": 1896, "description": "梦想与幻灭，温柔而残忍"},
        ],
    },
    {
        "writer_id": "flaubert",
        "name": "居斯塔夫·福楼拜",
        "name_en": "Gustave Flaubert",
        "avatar_initial": "福",
        "bio": "1821—1880。法国现实主义作家，写一句话会改几十遍。",
        "personality_tags": ["严谨", "冷静", "精致", "现实"],
        "suitable_personality": "理性、严谨、追求真实、不喜浮夸",
        "suitable_life_state": "追求精准表达；讨厌虚伪；希望世界更清晰",
        "value_resonance": "真实高于情绪；严谨胜过随意",
        "suitable_timing": "想看清现实；拒绝自我欺骗；需要理性力量",
        "emotional_tone": "冷静、清晰、坚定",
        "contra_indicators": "喜欢浪漫幻想；需要情绪安慰；讨厌现实锋利",
        "recommendation_style": "你追求真实的性格，会被他极致的清醒深深吸引。",
        "works": [
            {"title": "包法利夫人", "year": 1857, "description": "现实主义经典，幻想与现实的致命碰撞"},
            {"title": "情感教育", "year": 1869, "description": "一代青年理想的幻灭史"},
        ],
    },
    {
        "writer_id": "yoshida_kenko",
        "name": "吉田兼好",
        "name_en": "Yoshida Kenko",
        "avatar_initial": "吉",
        "bio": "日本镰仓时代。法师、隐士，出家后隐居写《徒然草》。",
        "personality_tags": ["佛系", "通透", "淡泊", "禅意"],
        "suitable_personality": "安静、淡然、不喜纷争、内心平和",
        "suitable_life_state": "希望慢下来；厌倦内卷；追求内心宁静",
        "value_resonance": "顺其自然；看淡得失；平静即是幸福",
        "suitable_timing": "想放松、想放下焦虑、想回归简单",
        "emotional_tone": "安宁、松弛、淡然",
        "contra_indicators": "追求奋斗热血；需要目标驱动；喜欢强烈情绪",
        "recommendation_style": "你喜欢安静简单的生活，他会给你最舒服的松弛感。",
        "works": [
            {"title": "徒然草", "year": 1330, "description": "随笔集，无常与淡然的禅意美学"},
        ],
    },
    {
        "writer_id": "tolstoy",
        "name": "列夫·托尔斯泰",
        "name_en": "Leo Tolstoy",
        "avatar_initial": "托",
        "bio": "1828—1910。俄国文学巨匠，晚年离家出走，死在小火车站。",
        "personality_tags": ["深刻", "悲悯", "自省", "宏大"],
        "suitable_personality": "思想深刻、内心柔软、爱自省、追求灵魂价值",
        "suitable_life_state": "思考人生意义；追求精神成长；内心有强烈道德感",
        "value_resonance": "爱能拯救一切；精神高于物质",
        "suitable_timing": "迷茫、寻找方向；需要灵魂力量",
        "emotional_tone": "厚重、悲悯、被照亮",
        "contra_indicators": "只想轻松娱乐；拒绝深度思考；讨厌沉重",
        "recommendation_style": "你内心对意义的追寻，他会用最温柔的方式回应你。",
        "works": [
            {"title": "战争与和平", "year": 1869, "description": "史诗巨著，人类命运与灵魂救赎"},
            {"title": "安娜·卡列尼娜", "year": 1878, "description": "爱与道德的终极拷问"},
            {"title": "复活", "year": 1899, "description": "灵魂的救赎之路"},
        ],
    },
    {
        "writer_id": "rilke",
        "name": "莱内·马利亚·里尔克",
        "name_en": "Rainer Maria Rilke",
        "avatar_initial": "里",
        "bio": "1875—1926。奥地利诗人，一生漂泊，几乎无固定居所。",
        "personality_tags": ["诗意", "柔软", "孤独", "内省"],
        "suitable_personality": "内向、细腻、诗意、容易孤独但享受独处",
        "suitable_life_state": "需要独处充电；内心丰富但不轻易外露",
        "value_resonance": "孤独不是缺陷，是灵魂的空间",
        "suitable_timing": "独处、思考、内心整理时",
        "emotional_tone": "温柔、孤独、被拥抱、被理解",
        "contra_indicators": "喜欢热闹；需要陪伴；拒绝孤独感",
        "recommendation_style": "你独处时的那些思绪，他比谁都更懂。",
        "works": [
            {"title": "给一位年轻诗人的信", "year": 1929, "description": "关于孤独与创作的温柔指引"},
            {"title": "杜伊诺哀歌", "year": 1923, "description": "诗歌顶峰，存在与消逝的沉思"},
            {"title": "马尔特·劳里茨·布里格手记", "year": 1910, "description": "意识流小说，孤独者的内心世界"},
        ],
    },
    {
        "writer_id": "akutagawa",
        "name": "芥川龙之介",
        "name_en": "Ryunosuke Akutagawa",
        "avatar_initial": "芥",
        "bio": "1892—1927。日本短篇鬼才，太宰治是他忠实粉丝。",
        "personality_tags": ["犀利", "冷静", "看透人性"],
        "suitable_personality": "清醒、冷静、观察力强、不轻易相信表面",
        "suitable_life_state": "对人性保持理性；不喜欢煽情；追求真实",
        "value_resonance": "真实比善良更重要；清醒比安慰更可贵",
        "suitable_timing": "不想被欺骗；想看清人性；拒绝鸡汤",
        "emotional_tone": "冷澈、清醒、锋利、安心",
        "contra_indicators": "需要温暖治愈；喜欢童话；害怕现实残酷",
        "recommendation_style": "你这种清醒的人，就需要他这种不骗人的文字。",
        "works": [
            {"title": "罗生门", "year": 1915, "description": "人性自私的极简寓言"},
            {"title": "竹林中", "year": 1922, "description": "真相的多重性，无解的人性"},
            {"title": "河童", "year": 1927, "description": "讽刺人类文明的奇幻寓言"},
        ],
    },
    {
        "writer_id": "hardy",
        "name": "托马斯·哈代",
        "name_en": "Thomas Hardy",
        "avatar_initial": "哈",
        "bio": "1840—1928。英国小说家，晚年放弃小说，专心写诗。",
        "personality_tags": ["悲凉", "温柔", "自然", "沉静"],
        "suitable_personality": "温柔、细腻、略带忧伤、共情力强",
        "suitable_life_state": "情绪敏感；容易共情他人；相信命运感",
        "value_resonance": "温柔是力量；悲伤也有美感",
        "suitable_timing": "情绪柔软、需要深度陪伴、不想被强行治愈",
        "emotional_tone": "温柔忧伤、沉静、被拥抱",
        "contra_indicators": "追求快乐亢奋；讨厌伤感；需要积极激励",
        "recommendation_style": "你的温柔与敏感，在他这里会被完全接住。",
        "works": [
            {"title": "德伯家的苔丝", "year": 1891, "description": "命运与偏见，温柔而残酷"},
            {"title": "还乡", "year": 1878, "description": "故土与命运，宿命感弥漫"},
        ],
    },
    {
        "writer_id": "blake",
        "name": "威廉·布莱克",
        "name_en": "William Blake",
        "avatar_initial": "布",
        "bio": "1757—1827。英国诗人、画家，他的画与诗一样出名。",
        "personality_tags": ["浪漫", "神秘", "诗意", "天真"],
        "suitable_personality": "浪漫、幻想、纯真、灵魂自由",
        "suitable_life_state": "喜欢想象；追求精神世界；不愿被现实束缚",
        "value_resonance": "想象比现实更真实；灵魂比物质重要",
        "suitable_timing": "想逃离现实；追求美；需要灵魂自由",
        "emotional_tone": "梦幻、轻盈、被治愈",
        "contra_indicators": "极度现实；拒绝幻想；喜欢理性逻辑",
        "recommendation_style": "你内心的浪漫与天真，他会帮你好好守护。",
        "works": [
            {"title": "天真之歌与经验之歌", "year": 1794, "description": "纯真与腐化，双面人性的诗意对照"},
        ],
    },
    {
        "writer_id": "boccaccio",
        "name": "薄伽丘",
        "name_en": "Giovanni Boccaccio",
        "avatar_initial": "薄",
        "bio": "1313—1375。意大利人文主义作家，《十日谈》是欧洲第一部短篇小说集。",
        "personality_tags": ["生动", "烟火气", "幽默", "真实"],
        "suitable_personality": "开朗、真实、热爱生活、不装",
        "suitable_life_state": "喜欢人间烟火；享受日常小事；真实坦率",
        "value_resonance": "生活本身就很美；真实最可贵",
        "suitable_timing": "想感受生活热气；需要轻松快乐",
        "emotional_tone": "温暖、生动、轻松、治愈",
        "contra_indicators": "喜欢高冷疏离；追求深刻严肃；讨厌世俗",
        "recommendation_style": "你热爱生活的真实样子，他最懂。",
        "works": [
            {"title": "十日谈", "year": 1353, "description": "欧洲第一部短篇小说集，世俗与人性的生动图鉴"},
        ],
    },
    {
        "writer_id": "wilde",
        "name": "奥斯卡·王尔德",
        "name_en": "Oscar Wilde",
        "avatar_initial": "王",
        "bio": "1854—1900。爱尔兰唯美主义作家，入狱后写下《深渊书简》。",
        "personality_tags": ["唯美", "毒舌", "骄傲", "通透"],
        "suitable_personality": "审美敏锐、骄傲通透、机智、不喜平庸",
        "suitable_life_state": "追求精神美感；讨厌虚伪世俗；喜欢优雅表达",
        "value_resonance": "美高于世俗道德；灵魂有趣比正确更重要",
        "suitable_timing": "想被机智点亮；想被美治愈；讨厌说教",
        "emotional_tone": "骄傲、清醒、优雅、被理解",
        "contra_indicators": "追求务实安稳；喜欢朴素低调；反感尖锐讽刺",
        "recommendation_style": "你骨子里的骄傲与审美，只有他能同频共振。",
        "works": [
            {"title": "道林·格雷的画像", "year": 1890, "description": "唯美主义宣言，美与道德的永恒悖论"},
            {"title": "不可儿戏", "year": 1895, "description": "最精彩的社会讽刺喜剧"},
            {"title": "深渊书简", "year": 1905, "description": "狱中忏悔录，骄傲灵魂的自我审判"},
        ],
    },
    {
        "writer_id": "maupassant",
        "name": "莫泊桑",
        "name_en": "Guy de Maupassant",
        "avatar_initial": "莫",
        "bio": "1850—1893。法国短篇之王，福楼拜是他的老师。",
        "personality_tags": ["冷静", "简练", "现实", "犀利"],
        "suitable_personality": "理性冷静、观察力强、不喜煽情、追求真实",
        "suitable_life_state": "看透人情世故；不喜欢鸡汤；偏爱冷静叙述",
        "value_resonance": "真实比温暖重要；清醒比安慰可贵",
        "suitable_timing": "想看清现实；不想被欺骗；需要冷静力量",
        "emotional_tone": "清醒、冷澈、利落、安心",
        "contra_indicators": "需要情绪安抚；喜欢浪漫幻想；讨厌现实锋利",
        "recommendation_style": "你这种不爱装的人，最适合他直白又冷静的文字。",
        "works": [
            {"title": "项链", "year": 1884, "description": "命运的反讽，一条项链改变一生"},
            {"title": "羊脂球", "year": 1880, "description": "战争中的人性，讽刺与悲悯并存"},
        ],
    },
    {
        "writer_id": "andersen",
        "name": "安徒生",
        "name_en": "Hans Christian Andersen",
        "avatar_initial": "安",
        "bio": "1805—1875。丹麦童话作家，一生未婚，孤独终老。",
        "personality_tags": ["纯真", "治愈", "柔软", "忧伤"],
        "suitable_personality": "内心柔软、共情力强、温柔细腻、容易感动",
        "suitable_life_state": "情绪敏感；需要温柔陪伴；相信善良与美好",
        "value_resonance": "温柔能治愈世界；善良值得被守护",
        "suitable_timing": "需要安慰、情绪脆弱、渴望温柔拥抱",
        "emotional_tone": "温暖、柔软、治愈、安心",
        "contra_indicators": "追求理性犀利；喜欢暗黑现实；讨厌温情",
        "recommendation_style": "你内心的柔软，需要他这种最纯粹的温柔来接住。",
        "works": [
            {"title": "海的女儿", "year": 1837, "description": "爱与牺牲，忧伤而纯美"},
            {"title": "卖火柴的小女孩", "year": 1845, "description": "最温柔的悲剧"},
            {"title": "丑小鸭", "year": 1843, "description": "关于自我认同与成长"},
        ],
    },
    {
        "writer_id": "twain",
        "name": "马克·吐温",
        "name_en": "Mark Twain",
        "avatar_initial": "吐",
        "bio": "1835—1910。美国幽默文学代表，「马克·吐温」是水手术语，意为安全水深。",
        "personality_tags": ["幽默", "讽刺", "自由", "少年气"],
        "suitable_personality": "开朗幽默、爱自由、不喜束缚、带少年气",
        "suitable_life_state": "喜欢冒险新鲜感；讨厌虚伪规矩；爱调侃生活",
        "value_resonance": "自由高于一切；幽默是生活解药",
        "suitable_timing": "想放松大笑；想被轻松治愈；讨厌沉重",
        "emotional_tone": "轻松、明亮、幽默、畅快",
        "contra_indicators": "喜欢深沉严肃；追求哲学；反感玩笑",
        "recommendation_style": "你心里那份少年气与自由，他最懂。",
        "works": [
            {"title": "哈克贝利·费恩历险记", "year": 1884, "description": "自由与成长，美国文学的灵魂"},
            {"title": "汤姆·索亚历险记", "year": 1876, "description": "少年气的冒险经典"},
        ],
    },
    {
        "writer_id": "balzac",
        "name": "巴尔扎克",
        "name_en": "Honoré de Balzac",
        "avatar_initial": "巴",
        "bio": "1799—1850。法国现实主义大师，喝咖啡成瘾，一天几十杯。",
        "personality_tags": ["现实", "宏大", "犀利", "社会观察"],
        "suitable_personality": "理性深刻、观察力强、关注社会、不喜表面",
        "suitable_life_state": "思考社会规则；看透人性复杂；追求真实结构",
        "value_resonance": "理解世界复杂；不简单黑白二分",
        "suitable_timing": "想理解社会；想看清人性逻辑；需要深度现实",
        "emotional_tone": "厚重、清醒、深刻、踏实",
        "contra_indicators": "追求轻松治愈；喜欢浪漫幻想；讨厌现实沉重",
        "recommendation_style": "你对现实的深刻好奇，他能给你最完整的答案。",
        "works": [
            {"title": "人间喜剧", "year": 1842, "description": "90余部作品构成的社会全景图"},
            {"title": "高老头", "year": 1835, "description": "父爱与社会冷漠的残酷对照"},
            {"title": "欧也妮·葛朗台", "year": 1833, "description": "吝啬鬼的世界，金钱与情感的战争"},
        ],
    },
    {
        "writer_id": "wells",
        "name": "H.G.威尔斯",
        "name_en": "H.G. Wells",
        "avatar_initial": "威",
        "bio": "1866—1946。英国科幻先驱，与居里夫人、爱因斯坦是朋友。",
        "personality_tags": ["前瞻", "理性", "科幻", "思考"],
        "suitable_personality": "理性、前瞻、逻辑强、关注人类未来",
        "suitable_life_state": "喜欢思考科技与社会；对未来保持好奇与警惕",
        "value_resonance": "理性审视文明；进步需伴随反思",
        "suitable_timing": "想思考未来；需要理性视角；讨厌空谈",
        "emotional_tone": "冷静、清醒、开阔、安定",
        "contra_indicators": "追求情感治愈；喜欢轻松故事；反感现实批判",
        "recommendation_style": "你理性又爱思考的特质，最适合他的清醒与远见。",
        "works": [
            {"title": "时间机器", "year": 1895, "description": "时间旅行的源头，对人类未来的警示"},
            {"title": "世界大战", "year": 1898, "description": "外星入侵，文明脆弱性的极致呈现"},
        ],
    },
    {
        "writer_id": "conrad",
        "name": "约瑟夫·康拉德",
        "name_en": "Joseph Conrad",
        "avatar_initial": "康",
        "bio": "1857—1924。英国作家，母语非英语，却成英文大师。",
        "personality_tags": ["深沉", "孤独", "人性探索"],
        "suitable_personality": "深沉、内向、爱思考人性本质、不喜表面",
        "suitable_life_state": "内心常自我追问；对文明与人性保持怀疑",
        "value_resonance": "人性幽暗是常态；清醒比乐观更真实",
        "suitable_timing": "想深入人性；需要深度陪伴；拒绝鸡汤",
        "emotional_tone": "沉静、冷峻、深刻、被理解",
        "contra_indicators": "追求轻松快乐；需要温暖安慰；讨厌沉重",
        "recommendation_style": "你内心深处的追问，只有他能真正回应。",
        "works": [
            {"title": "黑暗的心", "year": 1899, "description": "文明与黑暗，人性深渊的旅程"},
            {"title": "吉姆爷", "year": 1900, "description": "荣耀、懦弱与救赎"},
        ],
    },
    {
        "writer_id": "emily_bronte",
        "name": "艾米莉·勃朗特",
        "name_en": "Emily Brontë",
        "avatar_initial": "勃",
        "bio": "1818—1848。英国小说家，一生几乎不出家门，仅活30岁。",
        "personality_tags": ["热烈", "孤独", "狂野", "极致"],
        "suitable_personality": "情感浓烈、内心炽热、爱得极致、不喜平淡",
        "suitable_life_state": "情感强烈；爱憎分明；渴望灵魂共振",
        "value_resonance": "真实情感高于一切；极致才有意义",
        "suitable_timing": "情感汹涌；需要被理解热烈；不想被压抑",
        "emotional_tone": "炽热、浓烈、震撼、共鸣",
        "contra_indicators": "温和佛系；追求安稳；讨厌激烈情绪",
        "recommendation_style": "你骨子里的热烈与偏执，只有他能完全接住。",
        "works": [
            {"title": "呼啸山庄", "year": 1847, "description": "爱与恨的极致，灵魂的旷野之歌"},
        ],
    },
    {
        "writer_id": "yeats",
        "name": "W.B.叶芝",
        "name_en": "W.B. Yeats",
        "avatar_initial": "叶",
        "bio": "1865—1939。爱尔兰诗人，晚年获诺贝尔文学奖。",
        "personality_tags": ["浪漫", "诗意", "忧郁", "理想主义"],
        "suitable_personality": "浪漫、温柔、文艺、多愁善感",
        "suitable_life_state": "在情感与岁月中沉思；追求精神美感",
        "value_resonance": "美与诗意是生命底色；遗憾也是风景",
        "suitable_timing": "温柔情绪；思念；内心柔软时刻",
        "emotional_tone": "温柔、诗意、忧伤、被治愈",
        "contra_indicators": "极度理性；追求现实；讨厌感伤",
        "recommendation_style": "你温柔浪漫的灵魂，天生就该遇见他的诗。",
        "works": [
            {"title": "当你老了", "year": 1893, "description": "最著名情诗，时间与爱的永恒"},
            {"title": "驶向拜占庭", "year": 1928, "description": "生命与艺术，不朽的追寻"},
        ],
    },
    {
        "writer_id": "de_quincey",
        "name": "托马斯·德·昆西",
        "name_en": "Thomas De Quincey",
        "avatar_initial": "德",
        "bio": "1785—1859。英国作家，因鸦片瘾经历而成名。",
        "personality_tags": ["细腻", "内省", "忧郁", "心理"],
        "suitable_personality": "敏感、内省、情绪丰富、爱探索内心",
        "suitable_life_state": "内心思绪繁多；情绪细腻；常自我对话",
        "value_resonance": "内心真实最珍贵；情绪值得被看见",
        "suitable_timing": "独处反思；情绪细腻；需要被理解",
        "emotional_tone": "细腻、深邃、被看见、温柔",
        "contra_indicators": "粗线条性格；讨厌内心纠结；追求简单",
        "recommendation_style": "你细腻的内心世界，他比谁都更懂。",
        "works": [
            {"title": "一个英国鸦片吸食者的自白", "year": 1821, "description": "意识与幻觉的自传性探索"},
        ],
    },
    {
        "writer_id": "austen",
        "name": "简·奥斯汀",
        "name_en": "Jane Austen",
        "avatar_initial": "奥",
        "bio": "1775—1817。英国小说家，所有书都为女性发声。",
        "personality_tags": ["温柔", "理智", "优雅", "幽默"],
        "suitable_personality": "温和、优雅、理性、情感细腻、不喜冲突",
        "suitable_life_state": "追求情感与理性平衡；喜欢细腻人际观察",
        "value_resonance": "温柔而有风骨；理智不失温度",
        "suitable_timing": "想感受优雅情感；需要温和力量；拒绝狗血",
        "emotional_tone": "温柔、清醒、优雅、安心",
        "contra_indicators": "喜欢激烈冲突；追求刺激；讨厌细腻慢热",
        "recommendation_style": "你温和又有主见的样子，正是她笔下最动人的灵魂。",
        "works": [
            {"title": "傲慢与偏见", "year": 1813, "description": "爱情与理性，最优雅的相互理解"},
            {"title": "理智与情感", "year": 1811, "description": "两种性格，一种平衡"},
            {"title": "爱玛", "year": 1815, "description": "自我认知的成长故事"},
        ],
    },
    {
        "writer_id": "dostoevsky",
        "name": "陀思妥耶夫斯基",
        "name_en": "Fyodor Dostoevsky",
        "avatar_initial": "陀",
        "bio": "1821—1881。俄国文学巨匠，曾被判死刑，临刑赦免。",
        "personality_tags": ["痛苦", "深刻", "挣扎", "神性"],
        "suitable_personality": "思想极深、内心挣扎、敏感、追求灵魂答案",
        "suitable_life_state": "经历内心痛苦；不断自我追问；寻找救赎",
        "value_resonance": "痛苦孕育成长；灵魂比世俗更重要",
        "suitable_timing": "内心混乱；寻找意义；需要深度照亮",
        "emotional_tone": "沉重、深刻、被懂得、被救赎",
        "contra_indicators": "追求轻松快乐；拒绝深度；讨厌痛苦题材",
        "recommendation_style": "你灵魂深处的挣扎与追问，只有他能真正理解。",
        "works": [
            {"title": "罪与罚", "year": 1866, "description": "罪恶、良知与救赎的终极拷问"},
            {"title": "卡拉马佐夫兄弟", "year": 1880, "description": "信仰、道德与人性的史诗"},
            {"title": "白痴", "year": 1869, "description": "纯真的灵魂在黑暗世界里的命运"},
        ],
    },
    {
        "writer_id": "aesop",
        "name": "伊索",
        "name_en": "Aesop",
        "avatar_initial": "伊",
        "bio": "古希腊寓言家。传说相貌丑陋但智慧极高。",
        "personality_tags": ["简单", "通透", "道理", "现实"],
        "suitable_personality": "务实、清醒、直接、不喜绕弯",
        "suitable_life_state": "需要简单道理；讨厌复杂虚伪；追求实用",
        "value_resonance": "生存有规则；智慧胜过空谈",
        "suitable_timing": "需要清醒指引；想快速看懂人性",
        "emotional_tone": "清醒、直白、安定、通透",
        "contra_indicators": "追求情感浪漫；喜欢文艺抽象；讨厌现实",
        "recommendation_style": "你清醒务实的性格，最适合他一针见血的智慧。",
        "works": [
            {"title": "伊索寓言", "year": -600, "description": "人类最古老的智慧寓言集"},
        ],
    },
    {
        "writer_id": "dickens",
        "name": "查尔斯·狄更斯",
        "name_en": "Charles Dickens",
        "avatar_initial": "狄",
        "bio": "1812—1870。英国现实主义作家，童年贫困，一生同情穷人。",
        "personality_tags": ["温暖", "悲悯", "正义", "柔软"],
        "suitable_personality": "善良、心软、共情力强、有正义感",
        "suitable_life_state": "关心他人；希望世界更温柔；相信善良",
        "value_resonance": "善良是最强力量；正义不会缺席",
        "suitable_timing": "需要温暖力量；相信人间善意",
        "emotional_tone": "温暖、光明、治愈、安心",
        "contra_indicators": "追求冷酷现实；喜欢暗黑；讨厌温情",
        "recommendation_style": "你内心的善良与柔软，会被他最深地守护。",
        "works": [
            {"title": "双城记", "year": 1859, "description": "最好的时代，最坏的时代"},
            {"title": "雾都孤儿", "year": 1838, "description": "善良在黑暗里的坚持"},
            {"title": "远大前程", "year": 1861, "description": "成长、幻灭与真正的价值"},
        ],
    },
    {
        "writer_id": "hebel",
        "name": "约翰·彼得·黑贝尔",
        "name_en": "Johann Peter Hebel",
        "avatar_initial": "黑",
        "bio": "1760—1826。德国民间故事作家，身为牧师，故事来自民间。",
        "personality_tags": ["朴素", "温暖", "民间", "智慧"],
        "suitable_personality": "朴素、温和、踏实、喜欢简单美好",
        "suitable_life_state": "热爱日常小事；追求简单幸福；不喜复杂",
        "value_resonance": "平凡最珍贵；小生活有大智慧",
        "suitable_timing": "想回归简单；需要温暖治愈",
        "emotional_tone": "温暖、朴素、安心、治愈",
        "contra_indicators": "追求华丽刺激；喜欢深刻复杂；讨厌平淡",
        "recommendation_style": "你喜欢简单温暖的心，会被他的故事轻轻治愈。",
        "works": [
            {"title": "宝盒", "year": 1811, "description": "德国民间故事集，朴素中的大智慧"},
        ],
    },
    {
        "writer_id": "basho",
        "name": "松尾芭蕉",
        "name_en": "Matsuo Basho",
        "avatar_initial": "芭",
        "bio": "1644—1694。日本俳句圣手，一生旅行，死在旅途。",
        "personality_tags": ["清淡", "禅意", "寂静", "自然"],
        "suitable_personality": "安静、淡泊、极简、喜欢自然与寂静",
        "suitable_life_state": "追求内心平静；喜欢独处；远离喧嚣",
        "value_resonance": "简约即是富足；平静即是力量",
        "suitable_timing": "想慢下来；需要静心；回归自然",
        "emotional_tone": "清淡、安宁、空灵、松弛",
        "contra_indicators": "追求热闹刺激；喜欢强烈情绪；讨厌安静",
        "recommendation_style": "你淡泊安静的灵魂，最适合他的清寂与诗意。",
        "works": [
            {"title": "奥之细道", "year": 1689, "description": "旅途俳句，自然与无常的禅意"},
        ],
    },
    {
        "writer_id": "pu_songling",
        "name": "蒲松龄",
        "name_en": "Pu Songling",
        "avatar_initial": "蒲",
        "bio": "1640—1715。清代文学家，一生科举不顺，专写《聊斋》。",
        "personality_tags": ["奇幻", "温柔", "人情", "浪漫"],
        "suitable_personality": "浪漫、温柔、共情力强、相信世间温情",
        "suitable_life_state": "喜欢幻想故事；内心柔软；相信善意",
        "value_resonance": "真情超越生死；温柔最有力量",
        "suitable_timing": "需要温柔治愈；喜欢奇幻故事",
        "emotional_tone": "浪漫、温柔、治愈、安心",
        "contra_indicators": "极度现实理性；喜欢冷酷批判；讨厌温情",
        "recommendation_style": "你内心的温柔与浪漫，会被他的故事深深拥抱。",
        "works": [
            {"title": "聊斋志异", "year": 1740, "description": "鬼狐人情，比人更有情的异界故事"},
        ],
    },
    {
        "writer_id": "nietzsche",
        "name": "尼采",
        "name_en": "Friedrich Nietzsche",
        "avatar_initial": "尼",
        "bio": "1844—1900。德国哲学家，发疯后由妹妹照顾。",
        "personality_tags": ["狂傲", "深刻", "清醒", "强力"],
        "suitable_personality": "独立、狂傲、爱思考、不盲从、追求自我",
        "suitable_life_state": "拒绝被定义；不断自我超越；怀疑世俗",
        "value_resonance": "成为自己高于一切；价值由自己定义",
        "suitable_timing": "迷茫反叛；寻找自我；拒绝被规训",
        "emotional_tone": "狂傲、清醒、力量、被点燃",
        "contra_indicators": "追求安稳顺从；喜欢温和治愈；讨厌尖锐",
        "recommendation_style": "你不甘平庸的灵魂，天生就该与他相遇。",
        "works": [
            {"title": "查拉图斯特拉如是说", "year": 1883, "description": "超人哲学，最狂傲的精神宣言"},
            {"title": "悲剧的诞生", "year": 1872, "description": "酒神与日神，艺术与生命的对话"},
            {"title": "善恶的彼岸", "year": 1886, "description": "重估一切价值的哲学炸弹"},
        ],
    },
    {
        "writer_id": "woolf",
        "name": "弗吉尼亚·伍尔夫",
        "name_en": "Virginia Woolf",
        "avatar_initial": "伍",
        "bio": "1882—1941。意识流文学的先驱，投河自尽，口袋装满石头。",
        "personality_tags": ["意识流", "内省", "敏锐", "脆弱与力量并存"],
        "suitable_personality": "内向或矛盾型；习惯独处但渴望被深度理解的人；感受力强、容易过度思考的人",
        "suitable_life_state": "正在经历内在转变期；表面平静但内部有大量未解决的问题；需要独处空间却又感到孤独",
        "value_resonance": "重视内心真实胜过外部成就；对「普通生活里的深刻」有感知；不喜欢被简单安慰",
        "suitable_timing": "不想被励志、不想被教导、只想被「看见」的时候；正在重新审视自己和周围人的关系；生活节奏需要慢下来的阶段",
        "emotional_tone": "清醒感、被理解感、带有距离的温柔；不是治愈，是同行",
        "contra_indicators": "正在寻找行动指引的人；需要明确答案和结构感的人；情绪极度低落需要稳定锚点的人",
        "recommendation_style": "不说「你会喜欢她的书」，说「你现在的状态，刚好需要她那种清醒」",
        "works": [
            {"title": "达洛维夫人", "year": 1925, "description": "一天之内，一个女人的意识之流"},
            {"title": "到灯塔去", "year": 1927, "description": "时间、记忆与失去的哲学沉思"},
            {"title": "海浪", "year": 1931, "description": "六个声音，一部意识的交响乐"},
            {"title": "一间自己的房间", "year": 1929, "description": "论女性与写作，历久弥新的宣言"},
        ],
    },
    {
        "writer_id": "le_fanu",
        "name": "谢里丹·勒·法努",
        "name_en": "Sheridan Le Fanu",
        "avatar_initial": "法",
        "bio": "1814—1873。爱尔兰恐怖作家，现代心理恐怖先驱。",
        "personality_tags": ["诡异", "神秘", "心理", "暗黑"],
        "suitable_personality": "内向、敏感、喜欢心理氛围、不排斥暗黑",
        "suitable_life_state": "喜欢深夜独处；对心理恐惧有好奇；情绪偏细腻",
        "value_resonance": "真实恐惧来自内心；神秘比血腥更高级",
        "suitable_timing": "想体验心理氛围；喜欢暗黑美学；拒绝阳光鸡汤",
        "emotional_tone": "诡异、神秘、紧张、沉浸",
        "contra_indicators": "追求阳光快乐；胆小易害怕；讨厌压抑",
        "recommendation_style": "你偏爱幽暗氛围的内心，只有他能精准呼应。",
        "works": [
            {"title": "卡米拉", "year": 1872, "description": "女吸血鬼故事，心理恐怖的先驱"},
            {"title": "叔叔塞拉斯", "year": 1864, "description": "维多利亚时代的哥特悬疑经典"},
        ],
    },
    {
        "writer_id": "irving",
        "name": "华盛顿·欧文",
        "name_en": "Washington Irving",
        "avatar_initial": "欧",
        "bio": "1783—1859。美国文学之父，创造纽约文化形象。",
        "personality_tags": ["浪漫", "温柔", "传奇", "怀旧"],
        "suitable_personality": "浪漫、温柔、怀旧、喜欢故事与传说",
        "suitable_life_state": "喜欢慢节奏；向往旧时光；享受故事氛围",
        "value_resonance": "故事温暖人生；浪漫比现实更动人",
        "suitable_timing": "想逃离现实；需要温柔故事；放松心情",
        "emotional_tone": "温柔、浪漫、怀旧、治愈",
        "contra_indicators": "极度现实；追求刺激；讨厌慢节奏",
        "recommendation_style": "你温柔怀旧的气质，最适合他的浪漫故事。",
        "works": [
            {"title": "睡谷传奇", "year": 1820, "description": "无头骑士的传说，美国第一个经典恐怖故事"},
            {"title": "见闻札记", "year": 1820, "description": "美国第一部真正的文学作品集"},
        ],
    },
    {
        "writer_id": "pushkin",
        "name": "普希金",
        "name_en": "Alexander Pushkin",
        "avatar_initial": "普",
        "bio": "1799—1837。俄国文学之父，因决斗而死，年仅37。",
        "personality_tags": ["优雅", "自由", "热情", "诗意"],
        "suitable_personality": "浪漫、优雅、热爱自由、情感热烈",
        "suitable_life_state": "追求美与自由；不愿被束缚；情感真挚",
        "value_resonance": "自由无价；美与诗意是生命底色",
        "suitable_timing": "追求理想；感受自由；被美打动",
        "emotional_tone": "热烈、优雅、光明、力量",
        "contra_indicators": "务实保守；喜欢平淡；讨厌浪漫",
        "recommendation_style": "你热爱自由与美的灵魂，与他天生同频。",
        "works": [
            {"title": "叶甫盖尼·奥涅金", "year": 1833, "description": "俄国文学的百科全书式诗体小说"},
            {"title": "上尉的女儿", "year": 1836, "description": "动荡年代的爱情与忠诚"},
        ],
    },
    {
        "writer_id": "hoffmann",
        "name": "E.T.A.霍夫曼",
        "name_en": "E.T.A. Hoffmann",
        "avatar_initial": "霍",
        "bio": "1776—1822。德国浪漫派作家，《胡桃夹子》原作作者。",
        "personality_tags": ["奇幻", "神秘", "怪诞", "梦境"],
        "suitable_personality": "爱幻想、脑洞大、喜欢怪诞、超现实美感",
        "suitable_life_state": "沉浸想象世界；喜欢奇幻故事；不愿被现实限制",
        "value_resonance": "想象真实存在；梦境比现实更自由",
        "suitable_timing": "想逃离现实；追求奇幻美感；脑洞大开",
        "emotional_tone": "奇幻、神秘、梦幻、轻盈",
        "contra_indicators": "极度现实；拒绝幻想；喜欢理性逻辑",
        "recommendation_style": "你奇幻丰富的内心，最适合他的怪诞浪漫。",
        "works": [
            {"title": "胡桃夹子与鼠王", "year": 1816, "description": "童话与奇幻，柴可夫斯基芭蕾的原作"},
            {"title": "砂人", "year": 1817, "description": "心理恐怖的先驱，弗洛伊德的最爱"},
        ],
    },
    {
        "writer_id": "goethe",
        "name": "约翰·沃尔夫冈·歌德",
        "name_en": "Johann Wolfgang von Goethe",
        "avatar_initial": "歌",
        "bio": "1749—1832。德国文学巨匠，活83岁，跨越三个世纪。",
        "personality_tags": ["博大", "理性", "诗意", "智慧"],
        "suitable_personality": "成熟、稳重、理性、追求自我成长",
        "suitable_life_state": "人生进阶期；不断自我完善；思考人生整体",
        "value_resonance": "人生是自我完成；成长永不止步",
        "suitable_timing": "规划人生；需要智慧指引；追求成熟",
        "emotional_tone": "博大、安定、智慧、开阔",
        "contra_indicators": "追求年轻叛逆；喜欢激烈情绪；讨厌稳重",
        "recommendation_style": "你追求成长与成熟的心，会被他的智慧稳稳托住。",
        "works": [
            {"title": "浮士德", "year": 1832, "description": "人类追求与堕落的终极史诗"},
            {"title": "少年维特之烦恼", "year": 1774, "description": "青春情感的燃烧与幻灭"},
        ],
    },
    {
        "writer_id": "luxun",
        "name": "鲁迅",
        "name_en": "Lu Xun",
        "avatar_initial": "鲁",
        "bio": "1881—1936。浙江绍兴，中国现代文学奠基人，弃医从文。",
        "personality_tags": ["犀利", "清醒", "冷峻", "悲悯"],
        "suitable_personality": "清醒、正义、敏感、不愿麻木、敢于思考",
        "suitable_life_state": "关注现实；不愿自欺；希望世界变好",
        "value_resonance": "批判源于深爱；清醒高于麻木",
        "suitable_timing": "不愿被鸡汤麻痹；想看清现实；需要正义力量",
        "emotional_tone": "冷峻、清醒、力量、被点燃",
        "contra_indicators": "只想安逸；拒绝现实；讨厌沉重",
        "recommendation_style": "你不愿麻木的清醒，最需要他的文字来照亮。",
        "works": [
            {"title": "呐喊", "year": 1923, "description": "阿Q、孔乙己，国民性的精准解剖"},
            {"title": "彷徨", "year": 1926, "description": "知识分子的困境与出路"},
            {"title": "朝花夕拾", "year": 1928, "description": "童年回忆，温柔中的批判"},
        ],
    },
    {
        "writer_id": "yuhua",
        "name": "余华",
        "name_en": "Yu Hua",
        "avatar_initial": "余",
        "bio": "1960年生，浙江海盐，当代作家，早年是牙医。",
        "personality_tags": ["冷静", "残酷", "通透", "温柔"],
        "suitable_personality": "清醒、通透、内心强大、能直面现实",
        "suitable_life_state": "经历生活打磨；理解苦难；追求真实活着",
        "value_resonance": "活着本身就是意义；温柔藏在冷静里",
        "suitable_timing": "需要现实力量；拒绝鸡汤；直面人生",
        "emotional_tone": "冷静、通透、坚韧、被支撑",
        "contra_indicators": "追求梦幻治愈；害怕现实残酷；喜欢甜宠",
        "recommendation_style": "你清醒直面生活的样子，最适合他的文字。",
        "works": [
            {"title": "活着", "year": 1993, "description": "人是为活着本身而活着，而不是为活着之外的任何事物"},
            {"title": "许三观卖血记", "year": 1995, "description": "普通人的尊严与温柔"},
            {"title": "在细雨中呼喊", "year": 1991, "description": "童年记忆与命运的暗流"},
        ],
    },
    {
        "writer_id": "wang_zengqi",
        "name": "汪曾祺",
        "name_en": "Wang Zengqi",
        "avatar_initial": "汪",
        "bio": "1920—1997。江苏高邮，京派作家，沈从文弟子，文坛美食家。",
        "personality_tags": ["治愈", "细腻", "慢生活", "通透"],
        "suitable_personality": "温和、细腻、热爱生活、享受小美好",
        "suitable_life_state": "喜欢日常；追求安稳；希望慢下来",
        "value_resonance": "人间烟火最治愈；平淡即是幸福",
        "suitable_timing": "放松心情；感受生活；需要温柔治愈",
        "emotional_tone": "温暖、松弛、治愈、安心",
        "contra_indicators": "追求刺激激烈；喜欢深刻批判；讨厌平淡",
        "recommendation_style": "你热爱生活的温柔，会被他的文字轻轻拥抱。",
        "works": [
            {"title": "受戒", "year": 1980, "description": "纯净的青春与人间美好"},
            {"title": "大淖记事", "year": 1981, "description": "水乡烟火，最温柔的人情"},
            {"title": "人间草木", "year": 1990, "description": "植物与生活，散文中的小确幸"},
        ],
    },
    {
        "writer_id": "wang_xiaobo",
        "name": "王小波",
        "name_en": "Wang Xiaobo",
        "avatar_initial": "波",
        "bio": "1952—1997。北京作家，既是程序员也是作家。",
        "personality_tags": ["理性", "幽默", "自由", "反讽"],
        "suitable_personality": "独立、理性、爱自由、反套路、喜欢有趣",
        "suitable_life_state": "拒绝被规训；追求思想自由；讨厌愚昧",
        "value_resonance": "独立思考最可贵；有趣高于正确",
        "suitable_timing": "不想被说教；追求自由；需要理性幽默",
        "emotional_tone": "清醒、幽默、自由、畅快",
        "contra_indicators": "喜欢传统安稳；讨厌讽刺；拒绝反叛",
        "recommendation_style": "你追求自由与有趣的灵魂，天生就懂他。",
        "works": [
            {"title": "黄金时代", "year": 1992, "description": "自由与欲望，时代压抑下的反叛"},
            {"title": "沉默的大多数", "year": 1997, "description": "理性的反叛宣言"},
            {"title": "万寿寺", "year": 1999, "description": "历史与现实的平行叙事"},
        ],
    },
    {
        "writer_id": "liu_cixin",
        "name": "刘慈欣",
        "name_en": "Liu Cixin",
        "avatar_initial": "慈",
        "bio": "1963年生，山西，科幻作家，电力工程师出身。",
        "personality_tags": ["宏大", "理性", "科幻", "深邃"],
        "suitable_personality": "理性、逻辑强、格局大、喜欢宇宙与未来",
        "suitable_life_state": "思考人类文明；对宇宙好奇；追求宏大视角",
        "value_resonance": "文明存续优先；理性高于情绪",
        "suitable_timing": "想跳出个人情绪；需要宏大格局；思考未来",
        "emotional_tone": "宏大、冷静、开阔、安定",
        "contra_indicators": "追求情感细腻；喜欢日常小事；讨厌理性冰冷",
        "recommendation_style": "你理性宏大的格局，最适合他的宇宙尺度。",
        "works": [
            {"title": "三体", "year": 2008, "description": "宇宙文明的黑暗森林法则"},
            {"title": "流浪地球", "year": 2000, "description": "人类带着地球逃离太阳系"},
            {"title": "球状闪电", "year": 2005, "description": "量子世界与科学的边界"},
        ],
    },
    {
        "writer_id": "murakami",
        "name": "村上春树",
        "name_en": "Haruki Murakami",
        "avatar_initial": "村",
        "bio": "1949年生，日本作家，坚持长跑几十年。",
        "personality_tags": ["文艺", "孤独", "淡然", "治愈"],
        "suitable_personality": "内向、文艺、喜欢独处、孤独但自洽",
        "suitable_life_state": "都市独处；内心丰富；需要个人空间",
        "value_resonance": "孤独不可怕；自我陪伴最可靠",
        "suitable_timing": "独处放松；整理内心；需要温柔陪伴",
        "emotional_tone": "淡然、治愈、疏离、安心",
        "contra_indicators": "极度外向；需要陪伴；讨厌孤独感",
        "recommendation_style": "你独处时的温柔与平静，他最懂。",
        "works": [
            {"title": "挪威的森林", "year": 1987, "description": "青春、失去与孤独的柔软挽歌"},
            {"title": "海边的卡夫卡", "year": 2002, "description": "命运与逃离，寻找自我的成长"},
            {"title": "且听风吟", "year": 1979, "description": "第一部作品，夏日与孤独的开始"},
        ],
    },
    {
        "writer_id": "hemingway",
        "name": "海明威",
        "name_en": "Ernest Hemingway",
        "avatar_initial": "海",
        "bio": "1899—1961。美国作家，参加两次世界大战。",
        "personality_tags": ["硬汉", "直接", "克制", "力量"],
        "suitable_personality": "坚强、直接、克制、有骨气、不喜矫情",
        "suitable_life_state": "面对困难；保持尊严；不轻易认输",
        "value_resonance": "尊严高于一切；坚强是底色",
        "suitable_timing": "需要力量；遭遇挫折；保持骨气",
        "emotional_tone": "硬朗、坚定、力量、被鼓舞",
        "contra_indicators": "追求温柔治愈；喜欢细腻情绪；讨厌强硬",
        "recommendation_style": "你骨子里的坚强，会被他的文字彻底点燃。",
        "works": [
            {"title": "老人与海", "year": 1952, "description": "人可以被毁灭，但不能被打败"},
            {"title": "太阳照常升起", "year": 1926, "description": "迷失一代的清醒与坚硬"},
            {"title": "永别了武器", "year": 1929, "description": "战争中的爱情与幻灭"},
        ],
    },
    {
        "writer_id": "camus",
        "name": "阿尔贝·加缪",
        "name_en": "Albert Camus",
        "avatar_initial": "加",
        "bio": "1913—1960。法国存在主义作家，最年轻诺奖得主之一。",
        "personality_tags": ["清醒", "冷漠", "理性", "温柔"],
        "suitable_personality": "清醒、哲学、理性、看透世界但温柔",
        "suitable_life_state": "思考人生意义；面对荒诞；保持清醒",
        "value_resonance": "世界荒诞，但人可自我定义意义",
        "suitable_timing": "迷茫清醒；拒绝鸡汤；需要理性温柔",
        "emotional_tone": "冷静、清醒、温柔、被支撑",
        "contra_indicators": "追求热血励志；需要明确答案；讨厌荒诞",
        "recommendation_style": "你清醒的思考，最需要他这种温柔的理性。",
        "works": [
            {"title": "局外人", "year": 1942, "description": "荒诞中的清醒，最冷静的反抗"},
            {"title": "鼠疫", "year": 1947, "description": "荒诞世界里的人类抵抗"},
            {"title": "西西弗神话", "year": 1942, "description": "荒诞哲学的基石，反抗即意义"},
        ],
    },
    {
        "writer_id": "orwell",
        "name": "乔治·奥威尔",
        "name_en": "George Orwell",
        "avatar_initial": "奥",
        "bio": "1903—1950。英国作家，《1984》是警告不是预言。",
        "personality_tags": ["冷峻", "警示", "理性", "批判"],
        "suitable_personality": "理性、警惕、关注真相、不盲从",
        "suitable_life_state": "关注社会信息；保持独立思考；拒绝被控制",
        "value_resonance": "真相最重要；权力必须被警惕",
        "suitable_timing": "需要清醒警示；拒绝被洗脑；守护真实",
        "emotional_tone": "冷峻、清醒、坚定、安心",
        "contra_indicators": "追求轻松娱乐；喜欢浪漫；讨厌现实批判",
        "recommendation_style": "你保持清醒的坚持，最适合他的冷静警示。",
        "works": [
            {"title": "1984", "year": 1949, "description": "极权主义的终极预言，保持清醒的警钟"},
            {"title": "动物庄园", "year": 1945, "description": "权力腐化的寓言，简洁而深刻"},
        ],
    },
    {
        "writer_id": "kafka",
        "name": "弗兰茨·卡夫卡",
        "name_en": "Franz Kafka",
        "avatar_initial": "卡",
        "bio": "1883—1924。奥地利作家，死前要求烧毁全部作品。",
        "personality_tags": ["荒诞", "孤独", "敏感", "压抑"],
        "suitable_personality": "内向、敏感、孤独、常感格格不入",
        "suitable_life_state": "感到孤独压抑；不被理解；内心挣扎",
        "value_resonance": "孤独是本质；真实比乐观重要",
        "suitable_timing": "内心压抑；不被理解；需要被看见",
        "emotional_tone": "荒诞、孤独、沉重、被理解",
        "contra_indicators": "阳光开朗；追求快乐；讨厌压抑",
        "recommendation_style": "你不被世界理解的孤独，他完全懂得。",
        "works": [
            {"title": "变形记", "year": 1915, "description": "异化与孤独，现代人困境的隐喻"},
            {"title": "审判", "year": 1925, "description": "荒诞的权力机器与个体的无力"},
            {"title": "城堡", "year": 1926, "description": "永远抵达不了的目的地"},
        ],
    },
    {
        "writer_id": "marquez",
        "name": "加西亚·马尔克斯",
        "name_en": "Gabriel García Márquez",
        "avatar_initial": "马",
        "bio": "1927—2014。哥伦比亚作家，《百年孤独》让他一夜成名。",
        "personality_tags": ["魔幻", "浪漫", "史诗", "孤独"],
        "suitable_personality": "浪漫、史诗感、爱幻想、能接受孤独",
        "suitable_life_state": "喜欢宏大故事；沉浸想象；思考命运",
        "value_resonance": "孤独是宿命；浪漫超越现实",
        "suitable_timing": "想沉浸故事；追求浪漫史诗；感受命运",
        "emotional_tone": "魔幻、宏大、浪漫、震撼",
        "contra_indicators": "追求现实简单；喜欢轻松；讨厌复杂",
        "recommendation_style": "你内心的浪漫与史诗感，天生就该遇见他。",
        "works": [
            {"title": "百年孤独", "year": 1967, "description": "魔幻现实主义的顶峰，孤独的史诗"},
            {"title": "霍乱时期的爱情", "year": 1985, "description": "等待与爱情，跨越半个世纪"},
        ],
    },
    {
        "writer_id": "shakespeare",
        "name": "威廉·莎士比亚",
        "name_en": "William Shakespeare",
        "avatar_initial": "莎",
        "bio": "1564—1616。英国剧作家，一生37部戏剧。",
        "personality_tags": ["深刻", "戏剧", "浓烈", "人性"],
        "suitable_personality": "情感浓烈、观察力强、对人性有好奇",
        "suitable_life_state": "思考人情冷暖；面对爱恨；理解复杂人性",
        "value_resonance": "人性复杂多面；理解比批判重要",
        "suitable_timing": "想理解人性；感受强烈情感；需要深度",
        "emotional_tone": "浓烈、深刻、戏剧、被震撼",
        "contra_indicators": "喜欢简单平淡；追求轻松；讨厌复杂情绪",
        "recommendation_style": "你丰富浓烈的情感，最适合他的人性史诗。",
        "works": [
            {"title": "哈姆雷特", "year": 1603, "description": "生存还是毁灭，人性的终极追问"},
            {"title": "麦克白", "year": 1606, "description": "野心与罪恶，人性的堕落轨迹"},
            {"title": "罗密欧与朱丽叶", "year": 1597, "description": "最纯粹的爱情悲剧"},
        ],
    },
    {
        "writer_id": "tagore",
        "name": "泰戈尔",
        "name_en": "Rabindranath Tagore",
        "avatar_initial": "泰",
        "bio": "1861—1941。印度诗人，亚洲首位诺贝尔文学奖得主。",
        "personality_tags": ["温柔", "诗意", "治愈", "神性"],
        "suitable_personality": "温柔、诗意、内心柔软、信仰爱与美",
        "suitable_life_state": "追求心灵宁静；喜欢自然与美；相信爱",
        "value_resonance": "爱与美是生命本质；温柔最有力量",
        "suitable_timing": "需要治愈；感受美；心灵平静",
        "emotional_tone": "温柔、光明、神性、治愈",
        "contra_indicators": "理性现实；喜欢批判；讨厌温柔诗意",
        "recommendation_style": "你内心的柔软与美好，会被他的诗彻底治愈。",
        "works": [
            {"title": "吉檀迦利", "year": 1912, "description": "诺奖作品，神与爱的诗意颂歌"},
            {"title": "飞鸟集", "year": 1916, "description": "最美的短诗集，自然与人生的哲思"},
            {"title": "戈拉", "year": 1910, "description": "民族认同与人类普遍性的探索"},
        ],
    },
    {
        "writer_id": "higashino",
        "name": "东野圭吾",
        "name_en": "Keigo Higashino",
        "avatar_initial": "东",
        "bio": "1958年生，日本推理作家，工程师出身。",
        "personality_tags": ["理性", "悬疑", "人情", "温柔"],
        "suitable_personality": "理性、逻辑强、重感情、喜欢悬疑人性",
        "suitable_life_state": "喜欢解谜；关注人性动机；理性又温柔",
        "value_resonance": "人性复杂；善恶皆有缘由",
        "suitable_timing": "想解谜推理；理解人性；需要理性温柔",
        "emotional_tone": "冷静、悬疑、温暖、被安抚",
        "contra_indicators": "追求纯恐怖；喜欢热血；讨厌理性慢热",
        "recommendation_style": "你理性又重情的特质，最适合他的温柔推理。",
        "works": [
            {"title": "嫌疑人X的献身", "year": 2005, "description": "最纯粹的爱，以犯罪为形式"},
            {"title": "白夜行", "year": 1999, "description": "黑暗中相互依存的双生命运"},
            {"title": "解忧杂货店", "year": 2011, "description": "温柔治愈，时空交错中的善意"},
        ],
    },
    {
        "writer_id": "qian_zhongshu",
        "name": "钱钟书",
        "name_en": "Qian Zhongshu",
        "avatar_initial": "钱",
        "bio": "1910—1998。江苏无锡，文学大师，过目不忘，被称「文化昆仑」。",
        "personality_tags": ["幽默", "犀利", "智慧", "通透"],
        "suitable_personality": "聪明、通透、爱观察、喜欢机智幽默",
        "suitable_life_state": "看透世情；不盲从；喜欢机智表达",
        "value_resonance": "清醒通透最可贵；幽默是智慧",
        "suitable_timing": "想看清世情；需要机智清醒；拒绝鸡汤",
        "emotional_tone": "犀利、幽默、通透、畅快",
        "contra_indicators": "喜欢单纯温情；讨厌讽刺；拒绝清醒",
        "recommendation_style": "你通透机智的灵魂，最懂他的幽默与清醒。",
        "works": [
            {"title": "围城", "year": 1947, "description": "婚姻、人生与自我的讽刺寓言"},
            {"title": "管锥编", "year": 1979, "description": "学贯中西的文学评论巨著"},
        ],
    },
    {
        "writer_id": "lin_yutang",
        "name": "林语堂",
        "name_en": "Lin Yutang",
        "avatar_initial": "林",
        "bio": "1895—1976。福建漳州，作家，发明中文打字机。",
        "personality_tags": ["豁达", "幽默", "温和", "生活艺术家"],
        "suitable_personality": "豁达、温和、幽默、热爱生活、佛系",
        "suitable_life_state": "追求闲适；享受生活；不内卷不焦虑",
        "value_resonance": "生活的目的是快乐；自洽最珍贵",
        "suitable_timing": "放松心情；远离焦虑；需要生活智慧",
        "emotional_tone": "豁达、轻松、温暖、治愈",
        "contra_indicators": "追求奋斗热血；喜欢深刻批判；讨厌闲适",
        "recommendation_style": "你热爱生活的豁达，最适合他的温柔通透。",
        "works": [
            {"title": "生活的艺术", "year": 1937, "description": "闲适哲学，生活就是享受本身"},
            {"title": "京华烟云", "year": 1939, "description": "三代中国人的命运史诗"},
        ],
    },
    {
        "writer_id": "zhu_ziqing",
        "name": "朱自清",
        "name_en": "Zhu Ziqing",
        "avatar_initial": "朱",
        "bio": "1898—1948。江苏扬州，散文家，《背影》是对父亲最深思念。",
        "personality_tags": ["温柔", "细腻", "朴素", "真情"],
        "suitable_personality": "温和、内敛、重感情、细腻真诚",
        "suitable_life_state": "重视亲情；感受日常；内心柔软",
        "value_resonance": "真诚最动人；平淡见真情",
        "suitable_timing": "感受亲情；需要温柔力量；回归简单",
        "emotional_tone": "温暖、细腻、真诚、安心",
        "contra_indicators": "追求华丽刺激；喜欢犀利；讨厌平淡",
        "recommendation_style": "你真诚温柔的心，最适合他朴素动人的文字。",
        "works": [
            {"title": "背影", "year": 1925, "description": "父子情的极致表达，最朴素的感动"},
            {"title": "荷塘月色", "year": 1927, "description": "月下独行，最美的汉语散文之一"},
        ],
    },
    {
        "writer_id": "kawabata",
        "name": "川端康成",
        "name_en": "Yasunari Kawabata",
        "avatar_initial": "川",
        "bio": "1899—1972。日本作家，日本首位诺贝尔文学奖得主。",
        "personality_tags": ["纤细", "物哀", "安静", "凄美"],
        "suitable_personality": "细腻、敏感、安静、偏爱纤细凄美",
        "suitable_life_state": "喜欢安静独处；感受细微之美；情绪细腻",
        "value_resonance": "刹那即永恒；脆弱也是美",
        "suitable_timing": "静心感受美；情绪细腻；需要安静陪伴",
        "emotional_tone": "纤细、凄美、安静、治愈",
        "contra_indicators": "外向热烈；追求刺激；讨厌纤细忧伤",
        "recommendation_style": "你细腻敏感的美感，最适合他的物哀之美。",
        "works": [
            {"title": "雪国", "year": 1948, "description": "白雪与徒劳，日本物哀美学的极致"},
            {"title": "古都", "year": 1962, "description": "京都四季，美在消逝中的温柔"},
            {"title": "伊豆的舞女", "year": 1926, "description": "青春与邂逅，纯净的淡淡哀愁"},
        ],
    },
    {
        "writer_id": "crane",
        "name": "斯蒂芬·克莱恩",
        "name_en": "Stephen Crane",
        "avatar_initial": "克",
        "bio": "1871—1900。美国作家，28岁早逝，留下经典。",
        "personality_tags": ["现实", "冷静", "坚韧", "自然"],
        "suitable_personality": "理性、冷静、现实、坚韧、不喜煽情",
        "suitable_life_state": "面对现实残酷；保持坚韧；不喜鸡汤",
        "value_resonance": "现实冷酷但人可坚韧；真实高于安慰",
        "suitable_timing": "需要现实力量；拒绝煽情；直面困境",
        "emotional_tone": "冷静、现实、坚韧、安定",
        "contra_indicators": "追求浪漫治愈；喜欢温情；讨厌现实冷酷",
        "recommendation_style": "你冷静直面现实的性格，最适合他的真实力量。",
        "works": [
            {"title": "红色英勇勋章", "year": 1895, "description": "战争中的恐惧与成长，美国自然主义经典"},
            {"title": "街头女郎梅季", "year": 1893, "description": "底层现实的冷静记录"},
        ],
    },
    {
        "writer_id": "charlotte_bronte",
        "name": "夏洛蒂·勃朗特",
        "name_en": "Charlotte Brontë",
        "avatar_initial": "夏",
        "bio": "1816—1855。英国作家，三姐妹都是著名作家。",
        "personality_tags": ["独立", "坚韧", "情感浓烈"],
        "suitable_personality": "独立、自尊、坚韧、情感浓烈、不平则鸣",
        "suitable_life_state": "追求平等；维护尊严；不向现实低头",
        "value_resonance": "独立与尊严无价；爱情需平等",
        "suitable_timing": "需要自我力量；追求尊严；被鼓舞",
        "emotional_tone": "坚定、浓烈、力量、被点燃",
        "contra_indicators": "温和佛系；追求顺从；讨厌激烈",
        "recommendation_style": "你骨子里的独立与尊严，会被她深深点燃。",
        "works": [
            {"title": "简·爱", "year": 1847, "description": "女性独立与尊严的宣言，永恒的爱情经典"},
            {"title": "维莱特", "year": 1853, "description": "孤独与坚韧，更成熟的自传性书写"},
        ],
    },
    {
        "writer_id": "hesse",
        "name": "赫尔曼·黑塞",
        "name_en": "Hermann Hesse",
        "avatar_initial": "黑",
        "bio": "1877—1962。德国作家，年轻人的精神导师。",
        "personality_tags": ["内省", "孤独", "治愈", "成长"],
        "suitable_personality": "内省、孤独、追求自我、心灵成长",
        "suitable_life_state": "自我寻找期；内心成长；不断反思",
        "value_resonance": "人生终极任务是成为自己",
        "suitable_timing": "迷茫寻找自我；需要心灵指引；成长阶段",
        "emotional_tone": "内省、温柔、治愈、被指引",
        "contra_indicators": "追求外在成功；拒绝内心思考；讨厌孤独",
        "recommendation_style": "你寻找自我的旅程，他会一直陪你同行。",
        "works": [
            {"title": "悉达多", "year": 1922, "description": "灵魂寻道之旅，东西方智慧的融合"},
            {"title": "荒原狼", "year": 1927, "description": "孤独者的内心分裂与自我整合"},
            {"title": "玻璃球游戏", "year": 1943, "description": "精神与现实，诺奖作品"},
        ],
    },
    {
        "writer_id": "o_henry",
        "name": "欧·亨利",
        "name_en": "O. Henry",
        "avatar_initial": "亨",
        "bio": "1862—1910。美国短篇作家，「欧·亨利式结尾」成文学术语。",
        "personality_tags": ["温情", "幽默", "反转", "市井"],
        "suitable_personality": "温暖、善良、接地气、喜欢小故事",
        "suitable_life_state": "感受市井温暖；喜欢小人物善意；轻松治愈",
        "value_resonance": "平凡最珍贵；善良藏在日常",
        "suitable_timing": "需要轻松温暖；感受人间善意",
        "emotional_tone": "温暖、幽默、治愈、安心",
        "contra_indicators": "追求深刻严肃；喜欢暗黑；讨厌温情",
        "recommendation_style": "你温暖善良的心，最适合他的市井温柔。",
        "works": [
            {"title": "麦琪的礼物", "year": 1905, "description": "爱的牺牲，最温柔的反转"},
            {"title": "最后一片叶子", "year": 1907, "description": "希望与牺牲，人间温情"},
        ],
    },
    {
        "writer_id": "hugo",
        "name": "维克多·雨果",
        "name_en": "Victor Hugo",
        "avatar_initial": "雨",
        "bio": "1802—1885。法国浪漫主义领袖，法国为他举行国葬。",
        "personality_tags": ["浪漫", "宏大", "正义", "悲悯"],
        "suitable_personality": "理想主义、心怀大爱、正义、悲悯",
        "suitable_life_state": "关注社会；同情弱者；追求正义",
        "value_resonance": "善良与爱能拯救一切",
        "suitable_timing": "需要信仰力量；追求正义；感受大爱",
        "emotional_tone": "宏大、光明、悲悯、被鼓舞",
        "contra_indicators": "现实冷漠；追求利己；讨厌温情宏大",
        "recommendation_style": "你心怀大爱的理想主义，最适合他的悲悯与光明。",
        "works": [
            {"title": "悲惨世界", "year": 1862, "description": "救赎与善良，人类苦难中的光"},
            {"title": "巴黎圣母院", "year": 1831, "description": "美与丑，命运与爱的史诗"},
            {"title": "九三年", "year": 1874, "description": "革命与人性，宏大的道德追问"},
        ],
    },
    {
        "writer_id": "dazai",
        "name": "太宰治",
        "name_en": "Osamu Dazai",
        "avatar_initial": "太",
        "bio": "1909—1948。日本作家，多次自杀，最终投水。",
        "personality_tags": ["脆弱", "敏感", "颓废", "真诚"],
        "suitable_personality": "敏感、脆弱、柔软、容易共情、真诚",
        "suitable_life_state": "情绪低落；不被理解；内心敏感脆弱",
        "value_resonance": "脆弱不是罪；真实比坚强重要",
        "suitable_timing": "情绪脆弱；需要被接纳；不想被强行治愈",
        "emotional_tone": "忧伤、真诚、被理解、被拥抱",
        "contra_indicators": "阳光励志；追求积极；讨厌颓废忧伤",
        "recommendation_style": "你脆弱又真诚的灵魂，只有他能完全接纳。",
        "works": [
            {"title": "人间失格", "year": 1948, "description": "丧失做人资格，最真诚的自我剖析"},
            {"title": "斜阳", "year": 1947, "description": "没落贵族的挽歌，战后日本的忧伤"},
            {"title": "奔跑吧，梅勒斯", "year": 1940, "description": "信任与友情的纯粹寓言"},
        ],
    },
    {
        "writer_id": "fitzgerald",
        "name": "菲茨杰拉德",
        "name_en": "F. Scott Fitzgerald",
        "avatar_initial": "菲",
        "bio": "1896—1940。美国作家，妻子是他一生灵感与痛苦。",
        "personality_tags": ["浪漫", "忧伤", "华丽", "幻灭"],
        "suitable_personality": "浪漫、温柔、华丽、略带忧伤、爱梦想",
        "suitable_life_state": "追求美好；感受爱情；面对梦想与现实",
        "value_resonance": "梦想虽易碎，但依然值得追求",
        "suitable_timing": "温柔情绪；感受浪漫；面对遗憾",
        "emotional_tone": "华丽、忧伤、浪漫、被治愈",
        "contra_indicators": "极度现实；追求理性；讨厌忧伤浪漫",
        "recommendation_style": "你浪漫又易碎的心，最适合他的温柔忧伤。",
        "works": [
            {"title": "了不起的盖茨比", "year": 1925, "description": "美国梦的幻灭，最华丽的忧伤"},
            {"title": "夜色温柔", "year": 1934, "description": "爱情与毁灭，爵士时代的挽歌"},
        ],
    },
    {
        "writer_id": "mishima",
        "name": "三岛由纪夫",
        "name_en": "Yukio Mishima",
        "avatar_initial": "三",
        "bio": "1925—1970。日本作家，暴力美学文学大师。",
        "personality_tags": ["极致", "刚烈", "美学", "执念"],
        "suitable_personality": "浓烈、极致、执着、追求美与力量",
        "suitable_life_state": "追求极致体验；不接受平庸；性格刚烈",
        "value_resonance": "美在极致；宁为玉碎不为瓦全",
        "suitable_timing": "追求极致；需要刚烈力量；拒绝平庸",
        "emotional_tone": "浓烈、极致、刚烈、震撼",
        "contra_indicators": "温和佛系；追求平淡；讨厌激烈极致",
        "recommendation_style": "你不甘平凡的执念，只有他能真正共振。",
        "works": [
            {"title": "金阁寺", "year": 1956, "description": "美的执念与毁灭，极致的心理剖析"},
            {"title": "潮骚", "year": 1954, "description": "纯净的爱情，阳光下的力与美"},
            {"title": "丰饶之海", "year": 1970, "description": "四部曲，轮回与消亡的终极命题"},
        ],
    },
]


def seed(db):
    for w in SEED_WRITERS:
        writer_id = w["writer_id"]
        name = w["name"]
        name_en = w["name_en"]
        data = {k: v for k, v in w.items() if k not in ("writer_id", "name", "name_en")}
        db.upsert_writer(writer_id, name, name_en, data)
    print(f"[seed] {len(SEED_WRITERS)} writers loaded.")
